# Generated by Django 4.1.7 on 2023-05-20 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=250)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Secondary unit', 'Secondary unit'), ('Unique space', 'Unique space'), ('Bed and breakfast', 'Bed and breakfast'), ('Boutique hotel', 'Boutique hotel')], default='1', max_length=30)),
                ('stay_type', models.CharField(choices=[('Private room', 'Private room'), ('Shared property', 'Shared property'), ('Whole place', 'Whole place')], default='1', max_length=30)),
                ('beds', models.IntegerField(default=1)),
                ('baths', models.IntegerField(default=1)),
                ('guests', models.IntegerField(default=1)),
                ('preview', models.ImageField(upload_to='')),
                ('preview2', models.ImageField(default='house.jpg', null=True, upload_to='')),
                ('preview3', models.ImageField(default='house.jpg', null=True, upload_to='')),
                ('tv', models.BooleanField(default=False)),
                ('air_condition', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('hair_dryer', models.BooleanField(default=False)),
                ('heating', models.BooleanField(default=False)),
                ('iron', models.BooleanField(default=False)),
                ('workspace', models.BooleanField(default=False)),
                ('washer', models.BooleanField(default=False)),
                ('dryer', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('free_parking', models.BooleanField(default=False)),
                ('crib', models.BooleanField(default=False)),
                ('grill', models.BooleanField(default=False)),
                ('hot_tub', models.BooleanField(default=False)),
                ('EV_charger', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('indoor_fireplace', models.BooleanField(default=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyRanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertyranges', to='properties.property')),
            ],
        ),
    ]
